* Despliegue de aplicaciones con AWS Beanstalk
#+begin_quote
[!important]
Esta práctica la realizaremos en la *Landing Zone*. 
#+end_quote

En esta práctica realizaremos un despliegue de una aplicación *NodeJS* en AWS Beanstalk.

* Creación de una aplicación y entorno Beanstalk
En primer lugar, crearemos una aplicación Beanstalk y un entorno de ejecución. El nombre de la aplicación debe incluir tu *nombre y apellidos*.

Deberás crear *dos roles* (puedes hacerlo desde el propio asistente de Beanstalk):
- El rol para que Beanstalk pueda desplegar los recursos
- El rol que se utilizará como *perfil de instancia* de las instancias que lanzará Beanstalk

Como plataforma de aplicación, elige la última versión de *NodeJS*.

A la hora de seleccionar el código, elegiremos desplegar la *aplicación de prueba*.

* Subida manual del código
Clona el repositorio en tu equipo de trabajo si no lo has hecho ya. Accede a la carpeta del proyecto (~practicas-adman/06-beanstalk~) y comprime el contenido de dicha carpeta.

#+begin_quote
[!WARNING]
Recuerda que debes comprimir el *contenido de la carpeta* ~practicas-adman/06-beanstalk~, no la carpeta en sí. En la raíz del ZIP debe aparecer el fichero ~index.js~, no debe aparecer una carpeta en su interior.
#+end_quote

A continuación, accede al entorno de Beanstalk y sube el zip creado. Espera un tiempo, refresca la URL de la aplicación y comprueba que se muestra la web del proyecto.

* Actualización del código a través de la línea de comando
Si accedes al enlace que pone *Despedida*, verás que no funciona. En este apartado realizaremos una corrección del código y procederemos a desplegar la aplicación corregida.

** Preparación previa
Para evitar instalar todas las dependencias en nuestro equipo, utilizaremos el servicio *CloudShell* de AWS, que ya incorpora los comandos ~git~, ~npm~, ~aws~ y ~eb~.

Deberemos clonar el repositorio en CloudShell mediante el siguiente comando:
#+begin_src bash
git clone https://github.com/FormacionCloud/practicas-adman.git 
#+end_src

#+begin_quote
[!WARNING]
Si ya has clonado el repositorio anteriormente, en lugar de clonarlo deberás actualizar los cambios situándote en la carpeta del repositorio y ejecutando ~git pull~.
#+end_quote

A continuación, sitúate en la carpeta del proyecto (~practicas-adman/06-beanstalk~) y ejecuta el siguiente comando:
#+begin_src bash
  eb init
#+end_src

Responde a las preguntas que te indique:
1. Selecciona la región apropiada
2. Elige la opción que haga referencia a la aplicación Beanstalk que tengas creada
3. Selecciona el entorno correspondiente

Verás que al finalizar, se crea una carpeta denominada ~.ebextensions~. En ella se almacena la configuración del entorno para que futuras ejecuciones del comando ~eb~ puedan acceder a los datos del entorno correcto.

** Actualización de cambios y despliegue de la aplicación
Edita el fichero ~index.js~ (mediante el editor de tu elección, como por ejemplo ~nano~). Descomenta el código señalado como ~TODO~. A continuación, guarda los cambios en el fichero.

Seguidamente, ejecuta el siguiente comando para desplegar la aplicación actualizada:
#+begin_src bash
  eb deploy
#+end_src

Verás que la línea de comandos de Beanstalk realiza una serie de tareas para desplegar la aplicación:
1. Comprimir el contenido de la carpeta del proyecto
2. Seleccionar la aplicación y el entorno
3. Subir el fichero ZIP con los cambios del código de la aplicación
4. Reiniciar el entorno para que el nuevo código se ejecute correctamente

** Comprobación de resultados
Accede a la URL de la aplicación desplegada. Accede al enlace con el texto *Despedida* y comprueba que funciona correctamente.

** Eliminación del entorno de Beanstalk
Desde CloudShell, en la carpeta del proyecto, ejecuta el siguiente comando para eliminar el entorno:

#+begin_src bash
  eb terminate
#+end_src

* Entrega
Documenta la realización de la práctica explicando los pasos seguidos. Incluye las *capturas de pantalla* necesarias. Recuerda mostrar tus datos personales (nombre y apellidos y/o iniciales) en aquellos apartados donde se indique.

* Limpieza
Al finalizar, asegúrate que el entorno de Beanstalk se ha eliminado correctamente, para no incurrir en gastos innecesarios.
